TestTaskBISolutions/Models/ToDo.cs
namespace TestTaskBISolutions.Models
{
    public class ToDo
    {
        public Guid Id { get; set; }
        public string Content { get; set; } = string.Empty;
        public DateTime DateTimeCreating { get; set; } = DateTime.Now;
    }
}

TestTaskBISolutions/Controllers/Task1Controller.cs
using Microsoft.AspNetCore.Mvc;

namespace TestTaskBISolutions.Controllers
{
    public class Task1Controller : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Index(string numbers)
        {
            var numbersToDouble=numbers?.Trim().Split().Where(number=>!string.IsNullOrEmpty(number)).Select(int.Parse).ToList() ??new List<int>();
            var ans=SumSecondOddNumber(numbersToDouble);
            ViewBag.Numbers = numbers;
            return View(nameof(Index),ans);
        }
        public int SumSecondOddNumber(List<int> numbers)
        {
            var oddNumbers = numbers.Where(x => x % 2 != 0).ToList();
            var sumSecondOddNumbers = 0;
            for (int i = 0; i < oddNumbers.Count(); i+=2)
            {
                sumSecondOddNumbers += Math.Abs(oddNumbers[i]);
            }
            return sumSecondOddNumbers;
        }

    }
}

TestTaskBISolutions/Controllers/Task2Controller.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Linq;
using TestTaskBISolutions.Models;
namespace TestTaskBISolutions.Controllers
{
    public class Task2Controller : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(string str)
        {
            if (string.IsNullOrEmpty(str))
            {
                return View();
            }
            ViewBag.Str = str;
            return View(nameof(Index), IsPalindrome(str));
            
        }

        public bool IsPalindrome(string str)
        {
            
            var normolizeStr = string.Join("", str.ToLower().Trim().Split().Where(s => !string.IsNullOrEmpty(s)));
            int length = normolizeStr.Length;
            for (int i = 0; i < length; i++)
            {
                if (normolizeStr[i] != normolizeStr[^(i + 1)])
                    return false;
            }
            return true;
        }
    }
}

TestTaskBISolutions/Controllers/Task3Controller.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace TestTaskBISolutions.Controllers
{
    public class Task3Controller : Controller
    {
        public IActionResult Index()
        {
            var linkedList = new LinkedList { };
            
            for (int i = 10; i >= 0; i--)
            {
                linkedList.Add(i);
            }
            var originalLinkedList = linkedList.ToString();
            ViewBag.OriginalLinkedList = originalLinkedList;
            linkedList.Sort();
            var ans = linkedList.ToString();
            return View(nameof(Index),ans);
        }
    }
}

TestTaskBISolutions/Controllers/ToDoListController.cs
using Microsoft.AspNetCore.Mvc;
using TestTaskBISolutions.Data;
using TestTaskBISolutions.Interfaces;
using TestTaskBISolutions.Models;

namespace TestTaskBISolutions.Controllers
{
    public class ToDoListController : Controller
    {
        private IToDoListStorage toDoListStorage;
        public ToDoListController(IToDoListStorage toDoListStorage)
        {
            this.toDoListStorage = toDoListStorage;
        }
        public IActionResult Index()
        {
            var toDoList = toDoListStorage.GetAll();
            return View(toDoList);
        }

        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Add(string content)
        {
           toDoListStorage.Add(content);
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Edit(Guid id)
        {
            var toDo = toDoListStorage.GetById(id);
            return View(toDo);
        }
        [HttpPost]
        public IActionResult Edit(ToDo newContent)
        {
            toDoListStorage.Edit(newContent);
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Delete(Guid id)
        {
            toDoListStorage.Delete(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

TestTaskBISolutions/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TestTaskBISolutions</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TestTaskBISolutions.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="ToDoList" asp-action="Index">TestTaskBISolutions</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ToDoList" asp-action="Index">ToDoList</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Task1" asp-action="Index">Task1</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Task2" asp-action="Index">Task2</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Task3" asp-action="Index">Task3</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - TestTaskBISolutions - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TestTaskBISolutions/Views/Task1/Index.cshtml
@model int
<div class="row">
    <form asp-controller="Task1" asp-action="Index">
        <div class="col-12">
            <h2>Введите числа через пробел</h2>
        </div>
        <div class="col-4 mb-1">
            <input type="text" class="input-group" name="numbers"></input>
        </div>
        <div class="col-4">
            <button type="submit" class="btn btn-success">Посчитать</button>
        </div>
        <div class="col-4">
            @if (ViewBag.Numbers != null)
            {
                <h2>Сумма @Model</h2>
            }
        </div>
    </form>
</div>

TestTaskBISolutions/Views/Task2/Index.cshtml
@model bool

<div class="row">

    <form asp-controller="Task2" asp-action="Index">
        <div class="col-12">
            <h2>Введите строку</h2>
        </div>
        <div class="col-4 mb-1">
            <input type="text" name="str" class="input-group"></input>
        </div>
        <div class="col-4">
            <button type="submit" class="btn btn-success">Проверить</button>
        </div>

        <div class="col-4">
            @if (ViewBag.Str != null)
            {
                <h2>@(Model ? $"{ViewBag.Str} является полиндромом" : $"{ViewBag.Str} не является полиндромом")</h2>
            }
        </div>
    </form>
   

</div>

TestTaskBISolutions/Views/Task3/Index.cshtml
@model string
<p>Акулка бизнеса</p>
<p>Односвязный список: @ViewBag.OriginalLinkedList</p>
<p>Отсортированный односвязный список: @Model</p>

TestTaskBISolutions/Views/ToDoList/Add.cshtml
@model ToDo

<div class="row">
	<form method="post">
		<div class="col-6 card" style="margin-left:auto; margin-right:auto">
			<div class="card-header">
				<h5>Enter case data</h5>
			</div>
			<div class="card-body">
				<input type="text" asp-for="Content" class="form-control" placeholder="Content">
			</div>
			<div class="card-footer">
				<button type="submit" class="btn btn-success" style="150px" asp-controller="ToDoList" asp-action="Add">
					Add
				</button>
			</div>
		</div>
	</form>
</div>

TestTaskBISolutions/Views/ToDoList/Edit.cshtml
@model ToDo
<div class="row">
	<form method="post">
		<div class="col-6 card" style="margin-left:auto; margin-right:auto">
			<div class="card-header">
				<h5>Case data change</h5>
			</div>
			<div class="card-body">
				<input type="text" asp-for="Content" class="form-control" placeholder="Content">
			</div>
			<div class="card-footer">
				<button type="submit" class="btn btn-success" style="150px" asp-controller="ToDoList" asp-action="Edit">
					Edit
				</button>
			</div>
		</div>
	</form>
</div>

TestTaskBISolutions/Views/ToDoList/Index.cshtml
@model List<ToDo>
<div class="row">
	<div class="col-12 card">
		<table class="table">
			<thead>
				<tr>
					<th>Content</th>
					<th>Date and time of creating</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				@foreach (var toDo in Model)
				{
					<tr>
						<th class="w-50">@toDo.Content</th>
						<th>@toDo.DateTimeCreating</th>
						<th>
							<a class="btn btn-primary"  asp-controller="ToDoList" asp-action="Edit" asp-route-id="@toDo.Id">Edit</a>
							<a class="btn btn-danger"  asp-controller="ToDoList" asp-action="Delete" asp-route-id="@toDo.Id">Delete</a>
						</th>
					</tr>
				}				
			</tbody>			
		</table>		
	</div>
	<p></p>
	<a role="button" class="btn btn-success" style="width:150px" asp-controller="ToDoList" asp-action="Add">Add</a>
</div>